# Generated by Django 5.2.5 on 2025-08-31 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronic',
            old_name='type',
            new_name='brand',
        ),
    ]
